spring:
  datasource:
    url: jdbc:mysql://47.115.148.160:3306/ooa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: oaxt
    password: Wsw1533068154.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  jpa:
    show-sql: true

#  mail:
#    default-encoding: UTF-8
#    host: smtp.qq.com
#    username: 1254961594@qq.com
#    password: vhmvfsedpwtdbabi
#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#  thymeleaf:
#    cache: false
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8

server:
  port: 8888

mybatis:
  type-aliases-package: com.study.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

  logging:
    level:
      com:
        study:
          model:
            mdao:debug


