spring:
  datasource:
    url: jdbc:mysql://47.115.148.160:3306/jdoa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: oaxt
    password: Wsw1533068154.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  jpa:
    show-sql: true

server:
  port: 8888

mybatis:
  type-aliases-package: com.study.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

  logging:
    level:
      com.study.model.mdao : debug


